import fs from "node:fs";
import path from "node:path";
const root = path.resolve(import.meta.dirname, "..");
// Each lesson is deliberately short: concept, reasoning, example, practice and recall.
const areas = [
  [
    "financeira",
    "Financeira",
    "wallet",
    "Perceber dinheiro antes de decidir o que fazer com ele.",
    ["Fundamentos", "Orçamento"],
    [
      [
        "receitas-e-despesas",
        "O dinheiro entra ou sai?",
        "Receita é dinheiro que entra; despesa é dinheiro que sai.",
        "Um orçamento regista ambos no mesmo período. O saldo é a diferença entre receitas e despesas. Separar os movimentos ajuda a compreender as escolhas.",
        "Exemplo fictício: entram 50 € e gastas 18 €. O saldo é 32 €.",
        "Receber 50 € por um trabalho é…",
        ["uma receita", "uma despesa", "um empréstimo obrigatório"],
        0,
        "O pagamento recebido é uma entrada de dinheiro.",
        "Regista, em papel, uma entrada e uma saída de dinheiro. Não precisas de partilhar valores pessoais.",
        "receita rendimento despesa saldo dinheiro",
      ],
      [
        "necessidade-vs-desejo",
        "Necessidade ou desejo?",
        "Uma necessidade responde ao essencial; um desejo acrescenta algo que gostarias de ter.",
        "A distinção depende do contexto. Transporte para trabalhar pode ser essencial; uma melhoria estética pode esperar. Decidir prioridades não significa sentir culpa por ter desejos.",
        "Precisar de comer é diferente de querer jantar num restaurante caro.",
        "Qual é normalmente uma necessidade?",
        ["Uma consola nova", "Água potável", "Uma decoração nova"],
        1,
        "A água responde a uma necessidade básica.",
        "Escreve três necessidades e três desejos do teu dia.",
        "necessidade desejo prioridades gastos",
      ],
      [
        "planear-orcamento",
        "Dar um destino ao dinheiro",
        "Um orçamento é um plano para as entradas e saídas de um período.",
        "Começa pelo dinheiro disponível e pelos compromissos. Reserva espaço para imprevistos quando possível. Revê o plano quando a realidade mudar.",
        "Exemplo fictício: 50 € disponíveis, 30 € para compromissos e 10 € para outros gastos deixam 10 €.",
        "Se tens 50 € e planeias gastar 60 €, o plano…",
        [
          "tem 10 € de sobra",
          "não precisa de revisão",
          "excede o disponível em 10 €",
        ],
        2,
        "60 − 50 = 10 €. É preciso rever o plano ou as receitas.",
        "Faz um orçamento imaginário de 50 € que não ultrapasse esse valor.",
        "orçamento planeamento despesas fixas variáveis",
      ],
      [
        "poupanca-e-objetivos",
        "Poupar com um objetivo",
        "Poupar é guardar parte dos recursos de hoje para uma utilização futura.",
        "Um objetivo fica mais claro com valor e prazo. O dinheiro disponível para poupar varia entre pessoas e meses. Um plano é ajustável, não uma obrigação de atingir um valor universal.",
        "Exemplo sem juros: 5 € por semana durante 8 semanas somam 40 €.",
        "Sem juros, guardar 5 € em cada uma de 4 semanas soma…",
        ["20 €", "9 €", "40 €"],
        0,
        "5 × 4 = 20 €.",
        "Escolhe um objetivo fictício e divide o valor pelo número de semanas.",
        "poupança objetivos fundo emergência",
      ],
    ],
  ],
  [
    "digital",
    "Digital",
    "monitor",
    "Usar tecnologia com autonomia, segurança e consciência.",
    ["Segurança digital", "Organização"],
    [
      [
        "phishing",
        "Uma mensagem pede urgência",
        "Phishing é uma tentativa de enganar para obter dados, acesso ou dinheiro.",
        "Uma mensagem pode imitar uma entidade conhecida. A urgência e um pedido de código são sinais para parar. Confirma o pedido num canal oficial que já conheces.",
        "Uma SMS diz que a conta será bloqueada e pede o código de acesso através de um link.",
        "O que fazes primeiro?",
        [
          "Envias o código",
          "Abres o serviço pelo canal oficial para verificar",
          "Reencaminhas o código a um amigo",
        ],
        1,
        "Verificar por um canal independente reduz o risco de seguir uma mensagem falsa.",
        "Identifica dois sinais de pressão numa mensagem fictícia.",
        "phishing smishing fraude mensagem password",
      ],
      [
        "passwords-e-mfa",
        "Duas barreiras para a tua conta",
        "Uma palavra-passe única e a autenticação multifator ajudam a proteger o acesso.",
        "Evita reutilizar palavras-passe. Um gestor de palavras-passe pode ajudar a criar e guardar credenciais. MFA exige outro fator; os códigos de recuperação devem ficar num local seguro.",
        "Se uma palavra-passe reutilizada for exposta, várias contas podem ficar em risco.",
        "Qual é a opção mais prudente?",
        [
          "A mesma palavra-passe em todo o lado",
          "O nome do animal de estimação",
          "Palavras-passe únicas e MFA",
        ],
        2,
        "Combinar credenciais únicas e outro fator reduz riscos diferentes.",
        "Consulta as opções de segurança de uma conta, sem introduzir aqui credenciais.",
        "password passwords senha MFA autenticação contas",
      ],
      [
        "ficheiros-e-pastas",
        "Encontrar sem perder tempo",
        "Pastas e nomes claros tornam os ficheiros mais fáceis de encontrar.",
        "Agrupa por tema ou projeto. Usa nomes que indiquem conteúdo e data quando relevante. Evita muitas versões chamadas final sem outra identificação.",
        "recibo-2026-09.pdf é mais fácil de reconhecer do que documento123.pdf.",
        "Qual nome ajuda mais a encontrar um recibo?",
        ["recibo-2026-09.pdf", "coisa.pdf", "final-final2.pdf"],
        0,
        "O nome indica o conteúdo e o período.",
        "Desenha uma estrutura de três pastas para um projeto.",
        "ficheiro pasta organização download upload",
      ],
      [
        "backups",
        "Uma cópia que te pode salvar",
        "Um backup é uma cópia de recuperação dos teus ficheiros.",
        "Uma cópia noutro suporte reduz a dependência de um único dispositivo. A sincronização pode propagar eliminações; confirma se há histórico e recuperação. Testa recuperar um ficheiro sem apagar o original.",
        "O computador falha, mas uma cópia separada permite recuperar o trabalho.",
        "Qual situação protege melhor contra a falha do computador?",
        [
          "Só uma pasta no mesmo disco",
          "Uma cópia separada e recuperação testada",
          "Mudar o nome do ficheiro",
        ],
        1,
        "Uma cópia separada não depende apenas do disco original.",
        "Escolhe um ficheiro de teste e planeia onde guardar a cópia.",
        "backup cópia segurança cloud armazenamento",
      ],
    ],
  ],
  [
    "alimentar",
    "Alimentar",
    "utensils",
    "Compreender o que comemos, sem culpa e com mais autonomia.",
    ["Refeições", "Rótulos"],
    [
      [
        "variedade",
        "Variedade à mesa",
        "Uma alimentação variada combina alimentos de diferentes grupos ao longo do dia.",
        "Nenhum alimento, por si só, representa toda a alimentação. A Roda dos Alimentos ajuda a pensar na variedade e no equilíbrio. Preferências, acesso e necessidades individuais também contam.",
        "Alternar legumes, fruta, cereais e fontes de proteína acrescenta variedade.",
        "Qual proposta traz mais variedade?",
        [
          "Repetir apenas um alimento",
          "Excluir todos os legumes",
          "Combinar alimentos de diferentes grupos",
        ],
        2,
        "Grupos diferentes contribuem com nutrientes diferentes.",
        "Imagina uma refeição e identifica os grupos presentes.",
        "refeição variedade equilíbrio nutrientes",
      ],
      [
        "agua",
        "Dar espaço à água",
        "A água faz parte da alimentação e contribui para a hidratação.",
        "As necessidades variam com atividade, temperatura e situação individual. Ter água acessível pode ajudar a lembrar de beber. Não existe uma quantidade única adequada a todas as pessoas.",
        "Num passeio, levar água permite beber quando necessário.",
        "Qual medida facilita a hidratação no dia a dia?",
        [
          "Ter água acessível",
          "Evitar sempre água às refeições",
          "Usar apenas bebidas açucaradas",
        ],
        0,
        "A disponibilidade de água facilita a sua escolha.",
        "Planeia um momento do dia em que podes ter água por perto.",
        "água hidratação bebidas",
      ],
      [
        "ler-rotulos",
        "Comparar a mesma quantidade",
        "Para comparar rótulos, começa pelos valores por 100 g ou 100 ml.",
        "As porções indicadas nas embalagens podem ser diferentes. Compara produtos semelhantes na mesma base. Depois considera quanto vais consumir e lê os ingredientes.",
        "Dois iogurtes indicam porções diferentes; os valores por 100 g permitem uma comparação direta.",
        "Para comparar dois produtos semelhantes, usas…",
        [
          "porções de tamanhos diferentes",
          "valores por 100 g de ambos",
          "apenas a cor da embalagem",
        ],
        1,
        "A mesma quantidade permite uma comparação justa.",
        "Compara dois rótulos de produtos semelhantes, sem os classificar como bons ou maus.",
        "rótulos açúcar sal gordura fibra porção",
      ],
      [
        "ingredientes",
        "O que está na lista?",
        "A lista de ingredientes ajuda a conhecer a composição de um alimento.",
        "Na regra geral, os ingredientes aparecem por ordem decrescente de peso usado na preparação. A lista complementa a informação nutricional. Consulta também a indicação de alergénios quando relevante.",
        "Se a aveia aparece primeiro, é o ingrediente usado em maior quantidade, em regra.",
        "Em regra, o primeiro ingrediente é…",
        ["o mais caro", "o mais saudável", "o usado em maior quantidade"],
        2,
        "A ordem refere-se ao peso utilizado, não ao preço ou à qualidade nutricional.",
        "Lê os três primeiros ingredientes de uma embalagem.",
        "ingredientes composição alergénios rótulo",
      ],
    ],
  ],
  [
    "cientifica",
    "Científica",
    "flask",
    "Distinguir uma hipótese, a evidência e uma conclusão.",
    ["Método científico", "Pensamento crítico"],
    [
      [
        "hipotese",
        "Uma ideia que se pode testar",
        "Uma hipótese é uma explicação possível que pode ser confrontada com dados.",
        "Uma pergunta orienta a investigação. Uma hipótese faz uma previsão que pode falhar. Ajustar a ideia perante novos dados é parte do processo.",
        "Hipótese: plantas da mesma espécie crescem de forma diferente com quantidades diferentes de luz.",
        "Qual frase é uma hipótese testável?",
        [
          "Com mais luz, estas plantas crescem mais",
          "Esta planta é a mais bonita",
          "A ciência sabe tudo",
        ],
        0,
        "É possível comparar o crescimento em condições definidas.",
        "Transforma uma curiosidade numa pergunta que possas testar.",
        "pergunta hipótese experiência método",
      ],
      [
        "experiencia",
        "Comparar com cuidado",
        "Uma comparação é mais útil quando controla outras diferenças relevantes.",
        "Se mudas várias coisas ao mesmo tempo, é difícil perceber o que causou o resultado. Registar condições e repetir ajuda a avaliar a consistência. Uma experiência isolada não resolve todas as dúvidas.",
        "Ao testar luz, mantém semelhantes a água, o solo e a espécie das plantas.",
        "Para estudar o efeito da luz, convém…",
        [
          "mudar também solo e água",
          "manter outras condições semelhantes",
          "escolher só a planta que cresceu mais",
        ],
        1,
        "Controlar outras condições torna a comparação mais informativa.",
        "Desenha uma experiência com uma variável que muda e duas que manténs.",
        "experiência controlo dados replicação",
      ],
      [
        "correlacao",
        "Acontecer junto não prova a causa",
        "Correlação é uma relação entre variáveis; não demonstra por si só causalidade.",
        "Pode haver uma causa comum, coincidência ou influência em sentido inverso. Precisamos de mais evidência para explicar a relação. Uma associação pode ser útil sem provar uma causa.",
        "Vendas de gelados e idas à praia podem aumentar com o calor.",
        "Mais gelados vendidos e mais idas à praia provam que…",
        [
          "gelados causam idas à praia",
          "a praia fabrica gelados",
          "pode haver uma causa comum, como o calor",
        ],
        2,
        "O calor pode influenciar ambos os comportamentos.",
        "Procura uma terceira variável que explique uma associação imaginária.",
        "correlação causalidade causa coincidência",
      ],
      [
        "amostras",
        "Quem ficou de fora?",
        "Uma amostra é uma parte do grupo que queremos estudar.",
        "Uma amostra grande pode continuar enviesada se excluir pessoas relevantes. Pergunta como foram escolhidos os participantes. As conclusões devem respeitar os limites dos dados.",
        "Uma votação numa página sobre ciclismo não representa necessariamente toda a cidade.",
        "Para avaliar um inquérito, importa saber…",
        [
          "quem respondeu e como foi selecionado",
          "apenas a cor do gráfico",
          "se concordas com o resultado",
        ],
        0,
        "A seleção dos participantes influencia o que podemos concluir.",
        "Imagina quem fica de fora de um inquérito feito só online.",
        "amostra estatística viés evidência",
      ],
    ],
  ],
  [
    "ambiental",
    "Ambiental",
    "leaf",
    "Perceber como as nossas escolhas se ligam ao ambiente.",
    ["Recursos e resíduos", "Clima e consumo"],
    [
      [
        "reduzir-reutilizar",
        "Antes de deitar fora",
        "Reduzir e reutilizar evitam parte dos resíduos antes da reciclagem.",
        "Comprar apenas o necessário reduz materiais desperdiçados. Reparar ou reutilizar pode prolongar a vida dos objetos. A separação para reciclagem depende das regras locais.",
        "Usar um frasco que já tens evita comprar outro recipiente.",
        "Qual ação evita um resíduo logo na origem?",
        [
          "Comprar mais embalagens",
          "Reutilizar um recipiente adequado",
          "Misturar tudo no lixo",
        ],
        1,
        "Reutilizar pode evitar uma nova embalagem.",
        "Encontra um objeto que possas reutilizar com segurança.",
        "reduzir reutilizar reciclar resíduos",
      ],
      [
        "desperdicio",
        "Planear para desperdiçar menos",
        "Conhecer o que já tens ajuda a evitar compras que não vais usar.",
        "Uma lista pode partir do que existe em casa. Escolhe quantidades compatíveis com o uso previsto. Respeita as indicações de conservação e segurança dos produtos.",
        "Verificar a despensa antes de comprar evita duplicar um produto esquecido.",
        "Antes de fazer a lista de compras, é útil…",
        [
          "comprar tudo em promoção",
          "ignorar o que existe",
          "verificar o que já tens",
        ],
        2,
        "O inventário ajuda a comprar o necessário.",
        "Faz uma lista fictícia a partir de três produtos que já existem.",
        "desperdício planeamento consumo recursos",
      ],
      [
        "tempo-e-clima",
        "Hoje chove. E o clima?",
        "O tempo descreve condições momentâneas; o clima descreve padrões de longo prazo.",
        "Um dia frio não resume uma tendência climática. Para estudar padrões, usamos séries de observações ao longo de muitos anos. A escala de tempo muda a pergunta.",
        "A chuva desta tarde é tempo; a distribuição habitual da chuva numa região é clima.",
        "Uma previsão para amanhã descreve…",
        ["o tempo", "todo o clima futuro", "uma tendência de séculos"],
        0,
        "A previsão diária refere-se às condições meteorológicas de curto prazo.",
        "Escreve uma pergunta sobre o tempo e outra sobre o clima.",
        "clima tempo meteorologia padrões",
      ],
      [
        "ciclo-de-vida",
        "A história de um objeto",
        "O impacto de um produto inclui produção, transporte, uso e fim de vida.",
        "Comparar produtos exige olhar para mais do que a embalagem. Durabilidade, reparação e forma de utilização também contam. Uma alegação ambiental precisa de contexto e evidência.",
        "Um objeto reparável pode continuar útil em vez de ser substituído.",
        "Uma comparação ambiental completa considera…",
        [
          "só a cor verde da caixa",
          "várias fases da vida do produto",
          "só o nome da marca",
        ],
        1,
        "Os impactos podem ocorrer em fases diferentes.",
        "Desenha quatro etapas da vida de um objeto do quotidiano.",
        "ciclo de vida reparação sustentabilidade energia",
      ],
    ],
  ],
  [
    "juridica",
    "Jurídica",
    "scale",
    "Conhecer regras, direitos, deveres e caminhos para pedir apoio.",
    ["Contratos", "Consumidor"],
    [
      [
        "ler-contrato",
        "Antes de aceitar",
        "Um contrato pode criar direitos e obrigações para as partes.",
        "Lê as condições antes de aceitar. Preço, duração e condições de cessação ajudam a perceber o compromisso. Se algo não for claro, pede explicação e conserva uma cópia.",
        "Uma mensalidade baixa pode estar ligada a um período mínimo de contrato.",
        "Antes de aceitar uma subscrição, verificas…",
        [
          "só a cor do botão",
          "apenas o primeiro mês",
          "preço, duração e condições de cancelamento",
        ],
        2,
        "O compromisso inclui mais do que o preço inicial.",
        "Faz uma lista de três perguntas sobre uma subscrição fictícia.",
        "contrato aceitar assinar condições obrigações",
      ],
      [
        "direitos-e-deveres",
        "Os dois lados do acordo",
        "Um acordo pode atribuir direitos e deveres a ambas as partes.",
        "O consumidor pode ter de pagar o preço acordado e o fornecedor cumprir a prestação. As regras concretas dependem da lei e do contrato. Uma cláusula escrita não é automaticamente válida em qualquer situação.",
        "Num serviço combinado, cumprir o preço e prestar o serviço são compromissos diferentes.",
        "Um contrato deve ser lido para compreender…",
        ["direitos e deveres das partes", "só o título", "apenas a assinatura"],
        0,
        "Compreender as duas partes ajuda a perceber o acordo.",
        "Num acordo fictício, identifica um dever de cada parte.",
        "direito dever responsabilidade lei acordo",
      ],
      [
        "prova-de-compra",
        "Guardar para demonstrar",
        "A documentação ajuda a demonstrar uma compra e o que foi acordado.",
        "Conserva comprovativos, condições e comunicações relevantes. Registar datas torna mais fácil explicar um problema. Os documentos úteis variam consoante o caso.",
        "Um recibo e a confirmação da encomenda ajudam a identificar a compra.",
        "Que informação ajuda numa reclamação sobre uma encomenda?",
        [
          "Um comentário sem data",
          "Comprovativo e comunicações da compra",
          "Só a memória do preço",
        ],
        1,
        "Os registos ajudam a reconstruir os factos.",
        "Cria uma pasta fictícia com a lista dos documentos que guardarias.",
        "compra prova recibo garantia consumidor",
      ],
      [
        "reclamacao",
        "Explicar o problema com clareza",
        "Uma reclamação útil descreve factos, documentos e o resultado pretendido.",
        "Indica o que aconteceu e quando. Guarda cópia do que envias e usa os canais adequados. Para direitos e prazos concretos, consulta informação oficial atual ou apoio qualificado.",
        "A encomenda chegou incompleta: identifica o artigo em falta e junta o comprovativo.",
        "Qual início é mais útil numa reclamação?",
        [
          "Uma ameaça",
          "Uma lista de insultos",
          "A data, a compra e o problema observado",
        ],
        2,
        "Factos concretos tornam o pedido compreensível e verificável.",
        "Escreve três frases sobre um problema fictício, sem dados pessoais.",
        "reclamação consumidor recurso apoio",
      ],
    ],
  ],
  [
    "mediatica",
    "Mediática",
    "news",
    "Perceber quem criou uma mensagem e com que evidência.",
    ["Ler mensagens", "Verificar informação"],
    [
      [
        "facto-ou-opiniao",
        "Facto, opinião ou publicidade?",
        "Um facto pode ser verificado; uma opinião expressa uma avaliação.",
        "Uma notícia pode incluir ambos, que devem ser distinguidos. A publicidade procura promover algo. Identificar o tipo de mensagem ajuda a perceber a sua finalidade.",
        "O filme dura 90 minutos é verificável; é o melhor filme é uma avaliação.",
        "Qual frase expressa uma opinião?",
        [
          "Este é o melhor filme do ano",
          "A sessão começa às 18 h",
          "O bilhete custa 7 €",
        ],
        0,
        "Melhor é uma avaliação, não uma medição universal.",
        "Separa uma frase verificável de uma opinião num texto imaginário.",
        "notícia opinião publicidade facto sátira",
      ],
      [
        "conteudo-patrocinado",
        "Quem está a pagar?",
        "Conteúdo patrocinado envolve uma relação comercial que deve ser identificável.",
        "Uma recomendação pode ter incentivos económicos. Isso não prova que seja falsa, mas é contexto relevante. Procura a identificação de publicidade e avalia a evidência apresentada.",
        "Uma publicação recomenda um produto e indica parceria paga.",
        "A indicação parceria paga ajuda a perceber…",
        [
          "que tudo é falso",
          "que existe uma relação comercial",
          "que não há nenhum interesse",
        ],
        1,
        "O incentivo comercial faz parte do contexto da mensagem.",
        "Procura a forma como uma publicidade fictícia identifica o anunciante.",
        "patrocinado publicidade influência incentivos",
      ],
      [
        "fontes",
        "Voltar à origem",
        "Verificar uma afirmação começa por procurar a fonte original e o contexto.",
        "Pergunta quem publicou, quando e com que evidência. Várias páginas que copiam o mesmo texto não são confirmações independentes. Se não consegues verificar, podes esperar antes de partilhar.",
        "Uma captura de ecrã com uma frase não mostra necessariamente o documento completo.",
        "Qual passo melhora a verificação?",
        [
          "Contar apenas os gostos",
          "Partilhar antes de ler",
          "Procurar o documento original",
        ],
        2,
        "A fonte original permite verificar conteúdo, data e contexto.",
        "Escolhe uma afirmação fictícia e descreve a fonte que procurarias.",
        "fonte autor evidência verificação informação",
      ],
      [
        "imagens-fora-contexto",
        "Uma imagem, outra história",
        "Uma fotografia real pode ser usada com uma legenda enganadora.",
        "Verifica a data, o local e a origem. A imagem pode ser antiga ou mostrar outro acontecimento. Comparar com fontes independentes ajuda a reconstituir o contexto.",
        "Uma foto de uma inundação antiga é apresentada como se fosse de hoje.",
        "Antes de partilhar a imagem, verificas…",
        ["origem, data e local", "só a resolução", "se tem muitas partilhas"],
        0,
        "Uma imagem autêntica pode estar associada a um contexto falso.",
        "Lista três perguntas que farias sobre uma imagem viral.",
        "imagem contexto data desinformação viral",
      ],
    ],
  ],
  [
    "civica",
    "Cívica",
    "landmark",
    "Compreender as instituições e participar de forma informada.",
    ["Instituições", "Participação"],
    [
      [
        "instituicoes",
        "Quem trata deste assunto?",
        "Instituições diferentes têm competências diferentes.",
        "Um problema local e uma questão nacional podem exigir canais distintos. Consulta os contactos oficiais e confirma a competência. Se o destinatário não for o certo, pede orientação para o serviço adequado.",
        "Uma falha num espaço público municipal pode ser comunicada aos serviços municipais, confirmando a entidade responsável.",
        "Para comunicar um problema local, começas por…",
        [
          "enviar a todas as pessoas",
          "identificar o serviço competente",
          "escolher um partido ao acaso",
        ],
        1,
        "A competência ajuda a encaminhar o pedido.",
        "Escolhe um problema fictício e procura que tipo de serviço o trata.",
        "município freguesia governo instituições serviços",
      ],
      [
        "parlamento-e-governo",
        "Decidir, executar e fiscalizar",
        "Parlamento e Governo desempenham funções distintas no sistema político.",
        "Em Portugal, a Assembleia da República aprova leis e fiscaliza a atividade do Governo, entre outras funções. O Governo conduz a política geral e a administração pública. As competências são definidas pela Constituição.",
        "Uma pergunta parlamentar ao Governo é um exemplo de fiscalização política.",
        "Fiscalizar a atividade do Governo é uma função…",
        [
          "de qualquer loja",
          "apenas dos tribunais",
          "da Assembleia da República",
        ],
        2,
        "A fiscalização política do Governo integra as competências parlamentares.",
        "Consulta a descrição das funções de uma instituição num canal oficial.",
        "parlamento assembleia governo constituição",
      ],
      [
        "participar",
        "Há mais do que uma forma de participar",
        "Participar pode incluir votar, associar-se, apresentar petições e responder a consultas.",
        "Cada mecanismo tem condições próprias. Uma participação informada descreve o problema e considera os efeitos das propostas. Respeitar opiniões diferentes permite discutir soluções.",
        "Uma consulta pública pede contributos sobre uma proposta antes da decisão.",
        "Numa consulta pública, podes…",
        [
          "apresentar um contributo fundamentado",
          "substituir automaticamente a decisão final",
          "garantir a aprovação da tua proposta",
        ],
        0,
        "Uma consulta recolhe contributos; não garante um resultado específico.",
        "Escreve uma sugestão fundamentada para melhorar um espaço comum.",
        "participação voto petição consulta associação",
      ],
      [
        "dinheiro-publico",
        "De onde vem e para onde vai?",
        "O orçamento público prevê receitas e despesas de entidades públicas.",
        "Impostos são uma fonte de receita, mas não a única. As despesas refletem funções e escolhas públicas. Comparar previsão e execução ajuda a perceber o que foi planeado e realizado.",
        "Um orçamento pode prever verbas para manutenção de espaços públicos.",
        "A diferença entre previsão e execução mostra…",
        [
          "quem tem sempre razão",
          "o planeado e o realizado",
          "apenas a opinião de um cidadão",
        ],
        1,
        "Previsão é o plano; execução descreve o que ocorreu.",
        "Escolhe uma rubrica de um orçamento público e identifica o que representa.",
        "orçamento impostos receita despesa transparência",
      ],
    ],
  ],
  [
    "ia",
    "de IA",
    "sparkles",
    "Usar inteligência artificial com curiosidade e espírito crítico.",
    ["Compreender a IA", "Usar e verificar"],
    [
      [
        "modelos",
        "Padrões, não magia",
        "Um modelo de IA é um sistema ajustado a partir de dados para realizar tarefas.",
        "O treino permite aprender padrões. O desempenho depende da tarefa, dos dados e da forma de avaliação. Uma resposta fluente não demonstra compreensão humana nem garante exatidão.",
        "Um sistema pode classificar imagens com base em padrões aprendidos em exemplos.",
        "Uma resposta muito fluente é…",
        [
          "sempre verdadeira",
          "prova de consciência",
          "insuficiente para garantir exatidão",
        ],
        2,
        "A forma convincente de uma resposta não valida o conteúdo.",
        "Identifica uma tarefa em que a IA possa ajudar e um limite relevante.",
        "inteligência artificial modelo treino machine learning dados",
      ],
      [
        "alucinacoes",
        "Quando uma resposta inventa",
        "Uma IA generativa pode produzir informação incorreta com aparência convincente.",
        "Pode inventar nomes, referências ou detalhes. A confiança do tom não é uma medida de verdade. Quanto maiores as consequências, mais importante é verificar de forma independente.",
        "Uma referência bibliográfica parece real, mas não existe no catálogo indicado.",
        "Uma referência produzida por IA deve ser…",
        [
          "procurada e confirmada na fonte",
          "aceite porque tem um título",
          "partilhada sem abrir",
        ],
        0,
        "Confirmar a existência e o conteúdo evita confiar numa referência inventada.",
        "Cria uma lista de verificações para uma resposta de IA.",
        "alucinação erros fontes desatualizado",
      ],
      [
        "prompts",
        "Pedir com contexto",
        "Um pedido claro indica objetivo, contexto, restrições e resultado esperado.",
        "Explica para quem é a resposta e que formato ajuda. Fornece exemplos quando útil, sem dados sensíveis. Revê o resultado e ajusta o pedido se necessário.",
        "Resume este texto em cinco pontos, para alguém que está a começar, mantendo as incertezas.",
        "Qual pedido é mais claro?",
        [
          "Faz uma coisa",
          "Resume este parágrafo em três pontos para iniciantes",
          "Resolve tudo",
        ],
        1,
        "O pedido define tarefa, formato e público.",
        "Escreve um pedido com objetivo, contexto e uma restrição.",
        "prompt contexto objetivo restrições exemplos",
      ],
      [
        "verificar-ia",
        "Confirmar antes de usar",
        "Uma resposta de IA é um ponto de partida que precisa de revisão.",
        "Confirma factos em fontes adequadas e refaz cálculos importantes. Não partilhes dados privados sem compreender o serviço e a autorização necessária. A responsabilidade pela utilização não desaparece com a automatização.",
        "Um resumo pode omitir uma exceção importante do texto original.",
        "Antes de usar um resumo importante, deves…",
        [
          "confiar só no tom",
          "apagar o original",
          "comparar o resumo com o original",
        ],
        2,
        "A comparação permite encontrar omissões e alterações de sentido.",
        "Compara duas frases de um resumo fictício com o texto de origem.",
        "verificação privacidade autoria responsabilidade IA",
      ],
    ],
  ],
  [
    "seguranca",
    "de Segurança e Autoproteção",
    "shield",
    "Reconhecer riscos, afastar-se e saber pedir ajuda.",
    ["Prevenção", "Procurar ajuda"],
    [
      [
        "reconhecer-saidas",
        "Conhecer o espaço",
        "Identificar saídas e locais de apoio ajuda a planear uma saída segura.",
        "Observa o ambiente sem procurar confrontos. Em locais desconhecidos, identifica pessoas ou serviços que possam ajudar. Ajusta o percurso se te sentires inseguro.",
        "Ao chegar a um espaço, reparas na saída e no balcão de apoio.",
        "Num local desconhecido, uma medida prudente é…",
        [
          "identificar saídas e pontos de apoio",
          "procurar confrontos",
          "bloquear a saída",
        ],
        0,
        "Conhecer saídas e apoio facilita o afastamento e a procura de ajuda.",
        "Num desenho de um espaço fictício, marca a saída e um local de apoio.",
        "saídas ambiente risco prevenção deslocações",
      ],
      [
        "limites",
        "Podes afastar-te",
        "Respeitar limites inclui reconhecer quando queres interromper uma interação.",
        "Não tens de prolongar uma situação desconfortável para ser educado. Se possível, afasta-te para um local seguro e procura apoio. A responsabilidade por um comportamento abusivo é de quem o pratica.",
        "Uma pessoa insiste apesar de teres recusado; podes terminar a conversa e pedir ajuda.",
        "Perante uma interação invasiva, uma opção prudente é…",
        [
          "ficar para não parecer indelicado",
          "afastar-te e procurar apoio",
          "perseguir a pessoa",
        ],
        1,
        "Distância e apoio podem reduzir a exposição ao risco.",
        "Identifica uma pessoa ou serviço de confiança a quem poderias recorrer.",
        "limites consentimento comportamento invasivo segurança",
      ],
      [
        "evitar-escalada",
        "Não aumentar o confronto",
        "Numa situação de conflito, a prioridade é reduzir exposição e procurar segurança.",
        "Mantém distância quando possível e identifica uma saída. Procura apoio de pessoas ou autoridades. Evita perseguir ou tentar retaliar.",
        "Uma discussão cresce; sais para um local seguro em vez de acompanhar a provocação.",
        "Qual decisão favorece a segurança?",
        [
          "Perseguir o agressor",
          "Responder com uma ameaça",
          "Afastar-te e pedir ajuda",
        ],
        2,
        "Afastamento e ajuda reduzem a necessidade de confronto.",
        "Descreve uma saída segura para um cenário fictício, sem técnicas de combate.",
        "conflito distância saída ajuda autoproteção",
      ],
      [
        "ligar-112",
        "Pedir ajuda numa emergência",
        "Em Portugal, o 112 é o número para situações de emergência.",
        "Quando existe perigo imediato, procura segurança e contacta os serviços de emergência. Indica onde estás e o que aconteceu; responde às perguntas e segue as instruções. Não te coloques em perigo para recolher informação.",
        "Ao pedir ajuda, uma localização clara permite encaminhar a resposta.",
        "Que informação é prioritária na chamada?",
        [
          "Localização e descrição do que aconteceu",
          "Uma fotografia para publicar",
          "Uma opinião sobre quem tem culpa",
        ],
        0,
        "Os serviços precisam de localizar e compreender a emergência.",
        "Sem ligar, ensaia como descreverias a localização de um lugar conhecido.",
        "112 emergência localização socorro proteção contas password",
      ],
    ],
  ],
];
const sources = {
  financeira: [
    [
      "Todos Contam — rendimentos e despesas",
      "https://www.todoscontam.pt/pt-pt/node/443",
    ],
    [
      "Referencial de Educação Financeira",
      "https://www.todoscontam.pt/sites/default/files/SiteCollectionDocuments/ReferencialEducacaoFinanceira.pdf",
    ],
  ],
  digital: [
    ["CNCS — boas práticas", "https://dyn.cncs.gov.pt/pt/boaspraticas"],
    [
      "CNCS — autenticação multifator",
      "https://www.cncs.gov.pt/docs/guia-mfa.pdf",
    ],
  ],
  alimentar: [
    [
      "DGS — Roda dos Alimentos",
      "https://alimentacaosaudavel.dgs.pt/roda-dos-alimentos/",
    ],
    [
      "União Europeia — rotulagem alimentar",
      "https://europa.eu/youreurope/business/product-rules-compliance/food/labelling-rules/index_pt.htm",
    ],
  ],
  cientifica: [
    [
      "Understanding Science — Universidade da Califórnia",
      "https://undsci.berkeley.edu/understanding-science-101/",
    ],
  ],
  ambiental: [
    [
      "Agência Portuguesa do Ambiente — resíduos",
      "https://apambiente.pt/residuos",
    ],
    ["IPMA — clima", "https://www.ipma.pt/pt/oclima/"],
  ],
  juridica: [
    [
      "Your Europe — informação contratual",
      "https://europa.eu/youreurope/citizens/consumers/shopping/contract-information/index_pt.htm",
    ],
    [
      "gov.pt — conflitos de consumo",
      "https://www.gov.pt/guias/resolucao-de-conflitos-de-consumo",
    ],
  ],
  mediatica: [
    [
      "UNESCO — literacia mediática e informacional",
      "https://www.unesco.org/en/media-information-literacy",
    ],
  ],
  civica: [
    [
      "Assembleia da República — competências",
      "https://www.parlamento.pt/Parlamento/Paginas/Competencias.aspx",
    ],
  ],
  ia: [
    [
      "UNESCO — inteligência artificial",
      "https://www.unesco.org/en/artificial-intelligence",
    ],
  ],
  seguranca: [
    [
      "gov.pt — contactos de emergência",
      "https://www.gov.pt/guias/contactos-de-emergencia-em-portugal",
    ],
  ],
};
const scenarios = [
  [
    "Tens 50 €. Como divides?",
    "Tens 50 € e precisas de 30 € para um compromisso. Qual plano respeita o disponível?",
    [
      "30 € para o compromisso, 10 € para gastar e 10 € guardados",
      "40 € para lazer e 30 € para o compromisso",
      "Gastar 60 € sem rever o plano",
    ],
    0,
    "O primeiro plano soma 50 € e inclui o compromisso.",
    "Um convite custa 25 €, mas só tens 20 € livres depois dos compromissos. Como decides?",
    [
      "Ignorar os compromissos",
      "Rever o plano ou procurar uma alternativa dentro do disponível",
      "Assumir que os 5 € aparecem",
    ],
    1,
    "Um plano deve respeitar o dinheiro disponível e as prioridades.",
  ],
  [
    "Esta mensagem é phishing?",
    "Recebes uma SMS com urgência e um pedido de código. O que fazes?",
    [
      "Partilho o código",
      "Confirmo através do canal oficial, sem seguir o link",
      "Respondo com a palavra-passe",
    ],
    1,
    "A confirmação independente evita seguir um pedido suspeito.",
    "Uma mensagem diz que a tua cópia de segurança falhou e pede a senha. Como verificas?",
    [
      "Envio a senha",
      "Apago todas as cópias",
      "Abro diretamente o serviço conhecido e verifico o estado",
    ],
    2,
    "Abre o serviço pelo canal habitual e não envies credenciais pela mensagem.",
  ],
  [
    "Constrói uma refeição variada",
    "Qual proposta combina grupos diferentes?",
    ["Só arroz", "Só fruta", "Arroz, feijão, hortícolas e água"],
    2,
    "A combinação inclui vários grupos alimentares.",
    "Dois cereais têm porções diferentes no rótulo. Como os comparas?",
    [
      "Pelos valores por 100 g e pela lista de ingredientes",
      "Só pelo tamanho da caixa",
      "Só pela palavra natural",
    ],
    0,
    "A mesma base e os ingredientes ajudam a interpretar a composição.",
  ],
  [
    "O que conta como evidência?",
    "Uma afirmação sobre plantas fica mais sustentada por…",
    [
      "medições de uma comparação controlada",
      "um palpite sem teste",
      "a popularidade da frase",
    ],
    0,
    "Medições e condições descritas permitem avaliar a afirmação.",
    "Um inquérito numa página de desporto conclui que toda a cidade pratica desporto. Qual limite encontras?",
    [
      "Nenhum",
      "A amostra pode não representar a cidade",
      "A internet torna tudo falso",
    ],
    1,
    "A forma de seleção limita a generalização.",
  ],
  [
    "Menos desperdício",
    "Tens um objeto ainda utilizável. Qual ação pode prolongar a sua vida?",
    [
      "Deitar fora só porque é antigo",
      "Reparar ou reutilizar quando adequado",
      "Comprar dois substitutos",
    ],
    1,
    "Prolongar o uso pode evitar resíduos e novo consumo.",
    "Uma caixa diz ecológico sem explicar porquê. O que procuras?",
    [
      "Apenas a cor",
      "Uma promessa maior",
      "Evidência sobre materiais, produção, uso e fim de vida",
    ],
    2,
    "Uma alegação precisa de fundamento e contexto.",
  ],
  [
    "Antes de subscrever",
    "Uma subscrição anuncia preço baixo. O que verificas?",
    [
      "Só o anúncio",
      "Só o nome da empresa",
      "Preço total, duração e cancelamento",
    ],
    2,
    "São elementos relevantes para compreender o compromisso.",
    "Uma encomenda chega incompleta. Como preparas a reclamação?",
    [
      "Reúno prova, datas, descrição e pedido concreto",
      "Apago as comunicações",
      "Faço apenas ameaças",
    ],
    0,
    "Documentação e factos tornam o pedido verificável.",
  ],
  [
    "Notícia ou opinião?",
    "A frase esta é a melhor cidade para viver é…",
    ["uma avaliação", "um facto universal", "uma medição objetiva por si só"],
    0,
    "Melhor depende de critérios e valores que precisam de ser explicitados.",
    "Uma imagem antiga circula como sendo de hoje. O que fazes?",
    [
      "Partilho pela urgência",
      "Confirmo origem e data antes de partilhar",
      "Confio no número de gostos",
    ],
    1,
    "Verificar contexto evita amplificar informação enganadora.",
  ],
  [
    "Encaminhar um problema",
    "Queres comunicar um problema num espaço público. Começas por…",
    [
      "publicar dados pessoais de funcionários",
      "confirmar a entidade responsável e o canal oficial",
      "enviar a uma instituição ao acaso",
    ],
    1,
    "Competência e canal adequado ajudam a encaminhar o assunto.",
    "Queres contribuir para uma proposta em consulta pública. Qual passo é útil?",
    [
      "Assumir que o contributo é uma decisão",
      "Ignorar o texto",
      "Ler a proposta e apresentar uma sugestão fundamentada",
    ],
    2,
    "Um contributo informado relaciona a proposta com uma melhoria concreta.",
  ],
  [
    "Uma resposta convincente",
    "A IA apresenta uma referência para justificar uma afirmação. O que fazes?",
    [
      "Aceito sem ler",
      "Uso só o título",
      "Confirmo que existe e que sustenta a afirmação",
    ],
    2,
    "Uma referência pode ser inventada ou não sustentar o texto.",
    "Pedem-te um resumo de informação importante. Como usas IA?",
    [
      "Defino o objetivo e confiro o resultado no original",
      "Envio todos os dados privados sem avaliar",
      "Aceito qualquer resposta fluente",
    ],
    0,
    "Contexto e verificação continuam necessários.",
  ],
  [
    "Uma decisão prudente",
    "Num local desconhecido, uma interação torna-se ameaçadora. Qual é a prioridade?",
    [
      "Afastar-te para um local seguro e procurar ajuda",
      "Filmar de perto",
      "Perseguir a pessoa",
    ],
    0,
    "A prioridade é reduzir exposição e procurar segurança.",
    "Há perigo imediato e estás num local seguro. Ao contactar o 112, começas por…",
    [
      "publicar nas redes",
      "indicar a localização e o que aconteceu",
      "tentar descobrir culpados",
    ],
    1,
    "A localização e a situação ajudam a encaminhar a resposta.",
  ],
];
const data = areas.map(([id, name, icon, description, cats, rows], ai) => {
  const lessons = rows.map(
    (
      [
        lid,
        title,
        quick,
        explain,
        example,
        question,
        answers,
        correct,
        explanation,
        activity,
        words,
      ],
      i,
    ) => ({
      id: lid,
      title,
      summary: quick,
      quick,
      explain: [explain],
      example: { title: "Imagina", text: example },
      quiz: { question, answers, correct, explanation },
      experiment: {
        question: "Qual ideia levas deste exemplo?",
        answers: [
          quick,
          "Uma única situação permite tirar todas as conclusões.",
        ],
        correct: 0,
        explanation: quick,
      },
      activity,
      keywords: words.split(" "),
      aliases: words.split(" "),
      xp: 20,
      variants: {},
      minutes: 3,
    }),
  );
  const s = scenarios[ai];
  return {
    id,
    title: "Literacia " + name,
    shortTitle: ai === 9 ? "Segurança e Autoproteção" : ai === 8 ? "IA" : name,
    icon,
    description,
    categories: cats.map((title, i) => ({
      id: id + "-" + i,
      title,
      lessons: lessons.slice(i * 2, i * 2 + 2),
    })),
    mission: {
      id: "missao-" + id,
      title: s[0],
      question: s[1],
      answers: s[2],
      correct: s[3],
      explanation: s[4],
    },
    challenge: {
      id: "desafio-" + id,
      title: "Vida real",
      question: s[5],
      answers: s[6],
      correct: s[7],
      explanation: s[8],
    },
    sources: (sources[id] || []).map(([title, url]) => ({ title, url })),
  };
});
fs.mkdirSync(path.join(root, "data"), { recursive: true });
fs.writeFileSync(
  path.join(root, "data/literacies.json"),
  JSON.stringify(data, null, 2) + "\n",
);
// Classic script fallback also works when index.html is opened directly from disk.
fs.writeFileSync(
  path.join(root, "data/literacies.js"),
  "window.LITERACIES = " + JSON.stringify(data) + ";\n",
);
console.log(
  `${data.length} literacias; ${data.flatMap((a) => a.categories.flatMap((c) => c.lessons)).length} lições`,
);
